# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ddce85e01cc71b2e4728c951d6e63ee812844a186a6ccdb54a97bd86837880cd880cfd43a907f583332bd25bbc2c72ef4f4c3a1eec1e889a4526d80a18f54ff

test:
  secret_key_base: 0dfa69c090c95cb63b44a0963d388b7dab51dd0a185a70b0e6b12ac04f7ad5216c9140133c311bebdb23249fe6381c42d05c159d99c77bf388a96c59152ce57f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
